Console Error
FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/number-guru-backend/firestore/indexes?create_composite=ClZwcm9qZWN0cy9udW1iZXItZ3VydS1iYWNrZW5kL2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy9jYXRlZ29yaWVzL2luZGV4ZXMvXxABGgkKBW9yZGVyEAEaDQoJY3JlYXRlZEF0EAIaDAoIX19uYW1lX18QAg